namespace: openshift-lightspeed

llm:
  apiUrl: ""
  apiKey: ""
  provider: ""
  model: ""

featureGates:
  - MCPServer

mcpServer:
  name: openshift-mcp
  url: http://openshift-mcp-server.openshift-mcp.svc.cluster.local:8080/mcp
  timeout: 120

agentic:
  enabled: true
  operatorImage: quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/lightspeed-agentic-operator:on-pr-c4c48af25ee0df85b0fe850e733664f02d9c24d9
  githubRaw: https://raw.githubusercontent.com/openshift/lightspeed-agentic-operator/main
